-- Seed file for Linux Commands

INSERT INTO public.linux_commands (command_name, description, category, example_usage) VALUES
('ls', 'Lists files and directories in the current directory', 'File System', 'ls -la'),
('cd', 'Changes the current directory', 'File System', 'cd ~/Documents'),
('cp', 'Copies files or directories', 'File System', 'cp file1.txt file2.txt'),
('mv', 'Moves or renames files or directories', 'File System', 'mv file1.txt ~/Documents'),
('mkdir', 'Creates a new directory', 'File System', 'mkdir MyDirectory'),
('rm', 'Deletes files or directories', 'File System', 'rm file1.txt'),
('find', 'Searches for files based on various criteria', 'File System', 'find . -name file1.txt'),
('tree', 'Displays a tree-like representation of the directory structure', 'File System', 'tree -a'),
('pwd', 'Prints the current working directory', 'File System', 'pwd'),
('touch', 'Creates a new empty file', 'File System', 'touch file1.txt'),
('cat', 'Displays the contents of a file', 'File System', 'cat file1.txt'),
('less', 'Displays the contents of a file one page at a time', 'File System', 'less file1.txt'),
('more', 'Displays the contents of a file one page at a time', 'File System', 'more file1.txt'),
('head', 'Displays the first few lines of a file', 'File System', 'head -n 5 file1.txt'),
('tail', 'Displays the last few lines of a file', 'File System', 'tail -n 5 file1.txt'),
('stat', 'Displays information about a file or directory', 'File System', 'stat file1.txt'),
('file', 'Determines the type of a file', 'File System', 'file file1.txt'),
('du', 'Displays the disk usage of a file or directory', 'File System', 'du -sh ~/Documents'),
('df', 'Displays the disk usage of a file system', 'File System', 'df -h'),
('ln', 'Creates a symbolic link to a file or directory', 'File System', 'ln -s file1.txt link1.txt'),
('chmod', 'Changes the permissions of a file or directory', 'File System', 'chmod +x file1.txt'),
('chown', 'Changes the ownership of a file or directory', 'File System', 'chown user:group file1.txt'),
('chgrp', 'Changes the group ownership of a file or directory', 'File System', 'chgrp group file1.txt'),
('mkdir -p', 'Creates a new directory and its parents if they do not exist', 'File System', 'mkdir -p ~/Documents/MyDirectory'),
('rmdir', 'Deletes an empty directory', 'File System', 'rmdir MyDirectory'),
('cp -r', 'Copies a directory and its contents recursively', 'File System', 'cp -r MyDirectory ~/Documents'),
('mv -i', 'Moves a file or directory interactively, prompting for confirmation', 'File System', 'mv -i file1.txt ~/Documents'),
('rm -i', 'Deletes a file or directory interactively, prompting for confirmation', 'File System', 'rm -i file1.txt'),
('rm -r', 'Deletes a directory and its contents recursively', 'File System', 'rm -r MyDirectory'),
('find -type', 'Searches for files of a specific type', 'File System', 'find . -type f -name file1.txt'),
('find -size', 'Searches for files of a specific size', 'File System', 'find . -size +10M'),
('find -mtime', 'Searches for files modified within a specific time range', 'File System', 'find . -mtime -1'),
('find -perm', 'Searches for files with specific permissions', 'File System', 'find . -perm 755'),
('tar', 'Creates a tar archive of a file or directory', 'File System', 'tar -cvf archive.tar file1.txt'),
('tar -x', 'Extracts the contents of a tar archive', 'File System', 'tar -xvf archive.tar'),
('zip', 'Creates a zip archive of a file or directory', 'File System', 'zip archive.zip file1.txt'),
('unzip', 'Extracts the contents of a zip archive', 'File System', 'unzip archive.zip'),
('gzip', 'Compresses a file using gzip', 'File System', 'gzip file1.txt'),
('gunzip', 'Decompresses a file compressed with gzip', 'File System', 'gunzip file1.txt.gz'),
('bzip2', 'Compresses a file using bzip2', 'File System', 'bzip2 file1.txt'),
('bunzip2', 'Decompresses a file compressed with bzip2', 'File System', 'bunzip2 file1.txt.bz2'),
('diff', 'Compares the contents of two files', 'File System', 'diff file1.txt file2.txt'),
('patch', 'Applies a patch to a file', 'File System', 'patch file1.txt patch.txt'),
('rsync', 'Synchronizes files and directories across systems', 'File System', 'rsync -avz file1.txt user@host:~/Documents'),
('scp', 'Copies files securely over a network', 'File System', 'scp file1.txt user@host:~/Documents'),
('sftp', 'Transfers files securely over a network using the SFTP protocol', 'File System', 'sftp user@host'),
('mount', 'Mounts a file system', 'File System', 'mount /dev/sdb1 /mnt'),
('umount', 'Unmounts a file system', 'File System', 'umount /mnt'),
('fsck', 'Checks and repairs a file system', 'File System', 'fsck /dev/sdb1'),
('mkfs', 'Creates a new file system', 'File System', 'mkfs -t ext4 /dev/sdb1'),
('top', 'Displays real-time system activity', 'Process Management', 'top -c'),
('ps', 'Lists running processes', 'Process Management', 'ps aux'),
('kill', 'Terminates a process', 'Process Management', 'kill 1234'),
('htop', 'Interactive process viewer', 'Process Management', 'htop'),
('systemctl', 'Manages system services', 'System Management', 'systemctl status'),
('df', 'Displays disk usage', 'File System', 'df -h'),
('du', 'Estimates disk usage', 'File System', 'du -sh'),
('free', 'Displays memory and disk usage', 'System Information', 'free -m'),
('uname', 'Displays system information', 'System Information', 'uname -a'),
('uptime', 'Displays system uptime', 'System Information', 'uptime'),
('whoami', 'Displays current username', 'User Management', 'whoami'),
('groups', 'Displays user groups', 'User Management', 'groups'),
('id', 'Displays user and group information', 'User Management', 'id'),
('last', 'Displays recent login history', 'User Management', 'last'),
('w', 'Displays current system users', 'User Management', 'w'),
('pkill', 'Terminates a process by name', 'Process Management', 'pkill firefox'),
('pgrep', 'Searches for a process by name', 'Process Management', 'pgrep firefox'),
('nice', 'Runs a command with modified priority', 'Process Management', 'nice -n 10 command'),
('renice', 'Changes the priority of a running process', 'Process Management', 'renice -n 10 -p 1234'),
('killall', 'Terminates all processes with a given name', 'Process Management', 'killall firefox'),
('sysctl', 'Displays and modifies kernel parameters', 'System Management', 'sysctl -a'),
('ulimit', 'Displays and sets user limits', 'User Management', 'ulimit -a'),
('sar', 'Displays system activity information', 'System Information', 'sar -u'),
('mpstat', 'Displays CPU statistics', 'System Information', 'mpstat -P ALL'),
('vmstat', 'Displays virtual memory statistics', 'System Information', 'vmstat -s'),
('iostat', 'Displays I/O statistics', 'System Information', 'iostat -x'),
('lsb_release', 'Displays Linux distribution information', 'System Information', 'lsb_release -a'),
('lsblk', 'Displays block device information', 'File System', 'lsblk -d'),
('blkid', 'Displays block device attributes', 'File System', 'blkid'),
('fdisk', 'Displays and modifies disk partitions', 'File System', 'fdisk -l'),
('parted', 'Displays and modifies disk partitions', 'File System', 'parted -l'),
('mount', 'Displays and modifies mounted file systems', 'File System', 'mount -l'),
('umount', 'Unmounts a file system', 'File System', 'umount /mnt'),
('dfstat', 'Displays disk usage statistics', 'File System', 'dfstat -h'),
('ext4magic', 'Recovers deleted files on ext4 file systems', 'File System', 'ext4magic -r /dev/sda1'),
('tune2fs', 'Displays and modifies ext2/ext3/ext4 file system parameters', 'File System', 'tune2fs -l /dev/sda1'),
('e2fsck', 'Checks and repairs ext2/ext3/ext4 file systems', 'File System', 'e2fsck -f /dev/sda1'),
('mkfs', 'Creates a new file system', 'File System', 'mkfs.ext4 /dev/sda1'),
('mkswap', 'Creates a new swap space', 'File System', 'mkswap /dev/sda2'),
('swapon', 'Activates a swap space', 'File System', 'swapon /dev/sda2'),
('swapoff', 'Deactivates a swap space', 'File System', 'swapoff /dev/sda2'),
('fuser', 'Displays processes using a file or socket', 'Process Management', 'fuser -v /dev/sda1'),
('lsof', 'Displays open files and sockets', 'Process Management', 'lsof -i :80'),
('pmap', 'Displays memory map of a process', 'Process Management', 'pmap -d 1234'),
('strace', 'Traces system calls of a process', 'Process Management', 'strace -p 1234'),
('tcpdump', 'Captures and displays network traffic', 'Network Management', 'tcpdump -i eth0 -n -vv -s 0 -c 100'),
('netstat', 'Displays network connections and statistics', 'Network Management', 'netstat -anp'),
('ss', 'Displays socket statistics', 'Network Management', 'ss -t -a'),
('nmap', 'Scans network ports and services', 'Network Management', 'nmap -sT 192.168.1.1'),
('iftop', 'Displays network traffic in real-time', 'Network Management', 'iftop -i eth0'),
('htop', 'Interactive process viewer with network I/O', 'Process Management', 'htop -d 10'),
('ping', 'Test network connectivity', 'Network Diagnostics', 'ping google.com'),
('curl', 'Transfer data to or from a web server', 'Network Tools', 'curl https://example.com'),
('wget', 'Download files from the internet', 'Network Tools', 'wget https://example.com/file.txt'),
('netstat', 'Display network connections and statistics', 'Network Diagnostics', 'netstat -an'),
('nmap', 'Scan network ports and services', 'Network Security', 'nmap -sS 192.168.1.1'),
('ssh', 'Securely connect to a remote server', 'Remote Access', 'ssh user@remote-server'),
('iptables', 'Configure firewall rules', 'Network Security', 'iptables -A INPUT -p tcp --dport 80 -j ACCEPT'),
('ufw', 'Configure and manage firewall rules', 'Network Security', 'ufw allow http'),
('dig', 'Perform DNS lookups', 'Network Diagnostics', 'dig example.com'),
('whois', 'Retrieve domain registration information', 'Network Tools', 'whois example.com'),
('tcpdump', 'Capture and analyze network traffic', 'Network Diagnostics', 'tcpdump -i eth0'),
('wireshark', 'Graphically analyze network traffic', 'Network Diagnostics', 'wireshark -i eth0'),
('nslookup', 'Perform DNS lookups', 'Network Diagnostics', 'nslookup example.com'),
('host', 'Perform DNS lookups', 'Network Diagnostics', 'host example.com'),
('mtr', 'Trace network routes and packet loss', 'Network Diagnostics', 'mtr example.com'),
('traceroute', 'Trace network routes', 'Network Diagnostics', 'traceroute example.com'),
('ssh-keygen', 'Generate SSH key pairs', 'Remote Access', 'ssh-keygen -t rsa'),
('scp', 'Securely copy files over a network', 'Remote Access', 'scp file.txt user@remote-server:/path'),
('sftp', 'Securely transfer files over a network', 'Remote Access', 'sftp user@remote-server'),
('telnet', 'Connect to a remote server using the telnet protocol', 'Remote Access', 'telnet example.com 80'),
('netcat', 'Read and write network connections', 'Network Tools', 'netcat example.com 80'),
('socat', 'Establish two bidirectional byte streams', 'Network Tools', 'socat TCP4:example.com:80 -'),
('iftop', 'Display network traffic in real-time', 'Network Diagnostics', 'iftop -i eth0'),
('iptraf', 'Monitor and analyze network traffic', 'Network Diagnostics', 'iptraf -i eth0'),
('iperf', 'Measure network bandwidth and performance', 'Network Diagnostics', 'iperf -c example.com'),
('openvpn', 'Establish a secure VPN connection', 'Network Security', 'openvpn --config example.conf'),
('openssl', 'Manage SSL/TLS certificates and connections', 'Network Security', 'openssl s_client -connect example.com:443'),
('snort', 'Detect and prevent network intrusions', 'Network Security', 'snort -i eth0'),
('suricata', 'Detect and prevent network intrusions', 'Network Security', 'suricata -i eth0'),
('fail2ban', 'Block IP addresses that show signs of malicious activity', 'Network Security', 'fail2ban-client status'),
('denyhosts', 'Block IP addresses that show signs of malicious activity', 'Network Security', 'denyhosts -c'),
('tcpwrapper', 'Control access to network services', 'Network Security', 'tcpwrapper -l'),
('sshguard', 'Block IP addresses that show signs of malicious SSH activity', 'Network Security', 'sshguard -c'),
('portscan', 'Scan for open network ports', 'Network Security', 'portscan example.com'),
('nessus', 'Scan for network vulnerabilities', 'Network Security', 'nessus -i eth0'),
('openvas', 'Scan for network vulnerabilities', 'Network Security', 'openvas -i eth0'),
('nikto', 'Scan web servers for vulnerabilities', 'Network Security', 'nikto -h example.com'),
('dirbuster', 'Scan web servers for directories and files', 'Network Security', 'dirbuster -u example.com'),
('dnsrecon', 'Gather DNS information and detect vulnerabilities', 'Network Security', 'dnsrecon -d example.com'),
('masscan', 'Scan large networks for open ports', 'Network Security', 'masscan -i eth0 192.168.1.0/24'),
('zmap', 'Scan large networks for open ports', 'Network Security', 'zmap -i eth0 192.168.1.0/24'),
('mitmproxy', 'Intercept and analyze network traffic', 'Network Diagnostics', 'mitmproxy -i eth0'),
('ettercap', 'Intercept and analyze network traffic', 'Network Diagnostics', 'ettercap -i eth0'),
('tshark', 'Capture and analyze network traffic', 'Network Diagnostics', 'tshark -i eth0'),
('grep', 'Search for a pattern in one or more files', 'Text Search', 'grep ''pattern'' file.txt'),
('awk', 'Pattern scanning and text processing language', 'Text Processing', 'awk ''{print $1}'' file.txt'),
('sed', 'Stream editor for filtering and transforming text', 'Text Manipulation', 'sed ''s/old/new/g'' file.txt'),
('cut', 'Remove sections from each line of a file', 'Text Extraction', 'cut -d '','' -f 1 file.txt'),
('sort', 'Sort lines of text in a file', 'Text Sorting', 'sort file.txt'),
('uniq', 'Remove duplicate lines from a file', 'Text Deduplication', 'uniq file.txt'),
('wc', 'Count the number of lines, words, and characters in a file', 'Text Statistics', 'wc file.txt'),
('cat', 'Concatenate and display files', 'Text Display', 'cat file1.txt file2.txt'),
('less', 'Display a file one page at a time', 'Text Display', 'less file.txt'),
('tail', 'Display the last few lines of a file', 'Text Display', 'tail file.txt'),
('head', 'Display the first few lines of a file', 'Text Display', 'head file.txt'),
('tr', 'Translate or delete characters', 'Text Transformation', 'tr ''a'' ''b'' < file.txt'),
('paste', 'Merge lines from multiple files', 'Text Merging', 'paste file1.txt file2.txt'),
('join', 'Join two files based on a common field', 'Text Joining', 'join file1.txt file2.txt'),
('comm', 'Compare two sorted files line by line', 'Text Comparison', 'comm file1.txt file2.txt'),
('diff', 'Compare two files line by line', 'Text Comparison', 'diff file1.txt file2.txt'),
('fmt', 'Format text to a specified width', 'Text Formatting', 'fmt file.txt'),
('pr', 'Format text for printing', 'Text Formatting', 'pr file.txt'),
('col', 'Filter out reverse line feeds', 'Text Filtering', 'col file.txt'),
('fold', 'Wrap text to a specified width', 'Text Wrapping', 'fold -w 80 file.txt'),
('nl', 'Number lines of a file', 'Text Numbering', 'nl file.txt'),
('od', 'Dump files in octal and other formats', 'Text Dumping', 'od file.txt'),
('strings', 'Extract printable strings from a file', 'Text Extraction', 'strings file.txt'),
('iconv', 'Convert the character encoding of a file', 'Text Encoding', 'iconv -f utf-8 -t latin1 file.txt'),
('recode', 'Convert the character encoding of a file', 'Text Encoding', 'recode latin1..utf-8 file.txt'),
('aspell', 'Interactive spell checker', 'Text Checking', 'aspell check file.txt'),
('ispell', 'Interactive spell checker', 'Text Checking', 'ispell file.txt'),
('look', 'Display lines from a file that start with a given string', 'Text Search', 'look prefix file.txt'),
('mawk', 'Pattern scanning and text processing language', 'Text Processing', 'mawk ''{print $1}'' file.txt'),
('gawk', 'Pattern scanning and text processing language', 'Text Processing', 'gawk ''{print $1}'' file.txt'),
('nawk', 'Pattern scanning and text processing language', 'Text Processing', 'nawk ''{print $1}'' file.txt'),
('pg', 'Display a file one page at a time', 'Text Display', 'pg file.txt'),
('more', 'Display a file one page at a time', 'Text Display', 'more file.txt'),
('tsort', 'Perform a topological sort on a file', 'Text Sorting', 'tsort file.txt'),
('vis', 'Display non-printable characters in a file', 'Text Display', 'vis file.txt'),
('ul', 'Underline text', 'Text Formatting', 'ul file.txt'),
('colrm', 'Remove columns from a file', 'Text Extraction', 'colrm 1 2 file.txt'),
('column', 'Format text into columns', 'Text Formatting', 'column -t file.txt'),
('rev', 'Reverse the lines of a file', 'Text Transformation', 'rev file.txt'),
('tac', 'Concatenate and display files in reverse order', 'Text Display', 'tac file.txt'),
('csplit', 'Split a file into sections based on a pattern', 'Text Splitting', 'csplit file.txt ''/pattern/'''),
('csplit', 'Split a file into sections based on a pattern', 'Text Splitting', 'csplit file.txt ''/pattern/'''),
('split', 'Split a file into fixed-size pieces', 'Text Splitting', 'split -l 10 file.txt'),
('xargs', 'Build and execute commands from standard input', 'Text Processing', 'xargs -n 1 echo < file.txt'),
('apt', 'Package manager for Debian-based systems', 'Package Management', 'apt update'),
('apt-get', 'Package manager for Debian-based systems', 'Package Management', 'apt-get install firefox'),
('apt-cache', 'Search for packages in the cache', 'Package Management', 'apt-cache search firefox'),
('yum', 'Package manager for RPM-based systems', 'Package Management', 'yum install firefox'),
('yum-search', 'Search for packages', 'Package Management', 'yum search firefox'),
('pacman', 'Package manager for Arch Linux', 'Package Management', 'pacman -S firefox'),
('dpkg', 'Package manager for Debian-based systems', 'Package Management', 'dpkg -i package.deb'),
('rpm', 'Package manager for RPM-based systems', 'Package Management', 'rpm -i package.rpm'),
('tar', 'Create and extract archives', 'Archive Management', 'tar -czf archive.tar.gz files'),
('gzip', 'Compress files', 'Archive Management', 'gzip file.txt'),
('gunzip', 'Decompress files', 'Archive Management', 'gunzip file.gz'),
('zip', 'Create and extract zip archives', 'Archive Management', 'zip archive.zip files'),
('unzip', 'Extract zip archives', 'Archive Management', 'unzip archive.zip'),
('bzip2', 'Compress files', 'Archive Management', 'bzip2 file.txt'),
('bunzip2', 'Decompress files', 'Archive Management', 'bunzip2 file.bz2'),
('xz', 'Compress files', 'Archive Management', 'xz file.txt'),
('unxz', 'Decompress files', 'Archive Management', 'unxz file.xz'),
('7z', 'Create and extract 7z archives', 'Archive Management', '7z a archive.7z files'),
('7za', 'Create and extract 7z archives', 'Archive Management', '7za a archive.7z files'),
('rpm2cpio', 'Extract rpm archives', 'Archive Management', 'rpm2cpio package.rpm | cpio -idmv'),
('dpkg-deb', 'Extract deb archives', 'Archive Management', 'dpkg-deb -x package.deb output'),
('apt-mark', 'Show or set package markings', 'Package Management', 'apt-mark showmanual'),
('apt-key', 'Manage package signing keys', 'Package Management', 'apt-key list'),
('apt-ftparchive', 'Generate package indexes', 'Package Management', 'apt-ftparchive packages . > Packages'),
('yumdownloader', 'Download packages', 'Package Management', 'yumdownloader firefox'),
('yum-config-manager', 'Manage yum configuration', 'Package Management', 'yum-config-manager --enable repository'),
('pacman-key', 'Manage package signing keys', 'Package Management', 'pacman-key --list-keys'),
('makepkg', 'Build packages from source', 'Package Management', 'makepkg -s package'),
('repoquery', 'Query package repositories', 'Package Management', 'repoquery --list package'),
('createrepo', 'Create package repositories', 'Package Management', 'createrepo .'),
('dpkg-scanpackages', 'Scan packages and create indexes', 'Package Management', 'dpkg-scanpackages . > Packages'),
('apt-rdepends', 'Show package dependencies', 'Package Management', 'apt-rdepends firefox'),
('yum-deplist', 'Show package dependencies', 'Package Management', 'yum-deplist firefox'),
('pacman -Qi', 'Show package information', 'Package Management', 'pacman -Qi firefox'),
('dpkg -l', 'List installed packages', 'Package Management', 'dpkg -l'),
('rpm -qa', 'List installed packages', 'Package Management', 'rpm -qa'),
('yum list', 'List available packages', 'Package Management', 'yum list'),
('pacman -Ss', 'Search for packages', 'Package Management', 'pacman -Ss firefox'),
('apt-cache search', 'Search for packages', 'Package Management', 'apt-cache search firefox'),
('dpkg --listfiles', 'List package files', 'Package Management', 'dpkg --listfiles package'),
('rpm -ql', 'List package files', 'Package Management', 'rpm -ql package'),
('pacman -Ql', 'List package files', 'Package Management', 'pacman -Ql package'),
('yum provides', 'Find packages providing a file', 'Package Management', 'yum provides file'),
('apt-file search', 'Find packages providing a file', 'Package Management', 'apt-file search file'),
('pacman -Fs', 'Find packages providing a file', 'Package Management', 'pacman -Fs file'),
('useradd', 'Create a new user account', 'User Management', 'useradd -m -s /bin/bash newuser'),
('usermod', 'Modify an existing user account', 'User Management', 'usermod -aG sudo newuser'),
('userdel', 'Delete a user account', 'User Management', 'userdel newuser'),
('passwd', 'Change a user''s password', 'User Management', 'passwd newuser'),
('chpasswd', 'Change passwords for multiple users', 'User Management', 'chpasswd < users.txt'),
('groups', 'Display a user''s group membership', 'User Management', 'groups newuser'),
('id', 'Display a user''s ID and group membership', 'User Management', 'id newuser'),
('whoami', 'Display the current user''s username', 'User Management', 'whoami'),
('sudo', 'Execute a command with superuser privileges', 'Permissions', 'sudo apt update'),
('su', 'Switch to the superuser account', 'Permissions', 'su -'),
('chmod', 'Change the permissions of a file or directory', 'Permissions', 'chmod 755 file.txt'),
('chown', 'Change the ownership of a file or directory', 'Permissions', 'chown newuser file.txt'),
('chgrp', 'Change the group ownership of a file or directory', 'Permissions', 'chgrp newgroup file.txt'),
('setfacl', 'Set access control lists for a file or directory', 'Permissions', 'setfacl -m u:newuser:rwx file.txt'),
('getfacl', 'Display access control lists for a file or directory', 'Permissions', 'getfacl file.txt'),
('umask', 'Set the default permissions for new files and directories', 'Permissions', 'umask 022'),
('newgrp', 'Switch to a new group', 'User Management', 'newgrp newgroup'),
('sg', 'Execute a command with a different group membership', 'User Management', 'sg newgroup -c ''command'''),
('sudoers', 'Edit the sudoers file', 'Permissions', 'sudo visudo'),
('gpasswd', 'Administer the password for a group', 'User Management', 'gpasswd newgroup'),
('groupadd', 'Create a new group', 'User Management', 'groupadd newgroup'),
('groupmod', 'Modify an existing group', 'User Management', 'groupmod -n newgroup2 newgroup'),
('groupdel', 'Delete a group', 'User Management', 'groupdel newgroup'),
('getent', 'Display entries from databases supported by the Name Service Switch libraries', 'User Management', 'getent passwd newuser'),
('pwck', 'Verify the integrity of the password and group files', 'User Management', 'pwck'),
('grpck', 'Verify the integrity of the group file', 'User Management', 'grpck'),
('vipw', 'Edit the password file', 'User Management', 'vipw'),
('vigr', 'Edit the group file', 'User Management', 'vigr'),
('lastlog', 'Display the last login of all users or of a given user', 'User Management', 'lastlog -u newuser'),
('last', 'Display a list of the last logins on the system', 'User Management', 'last -a'),
('faillog', 'Display the contents of the failure log database', 'User Management', 'faillog -u newuser'),
('pam_tally', 'Interrogate the pam tally2 failure count file', 'User Management', 'pam_tally --user newuser'),
('pam_tally2', 'Interrogate the pam tally2 failure count file', 'User Management', 'pam_tally2 --user newuser'),
('authconfig', 'Configure user authentication', 'User Management', 'authconfig --update'),
('mkhomedir_helper', 'Create a user''s home directory', 'User Management', 'mkhomedir_helper newuser'),
('nscd', 'Name service cache daemon', 'User Management', 'nscd -i passwd start'),
('nsswitch.conf', 'Configure the Name Service Switch', 'User Management', 'nsswitch.conf passwd files'),
('pwhistory', 'Display password history for a user', 'User Management', 'pwhistory -u newuser'),
('pwconv', 'Convert to and from shadow passwords and user database', 'User Management', 'pwconv'),
('grpconv', 'Convert to and from shadow group database', 'User Management', 'grpconv'),
('pwunconv', 'Convert to and from shadow passwords and user database', 'User Management', 'pwunconv'),
('grpunconv', 'Convert to and from shadow group database', 'User Management', 'grpunconv'),
('chsh', 'Change a user''s shell', 'User Management', 'chsh -s /bin/bash newuser'),
('finger', 'Display information about a user', 'User Management', 'finger newuser'),
('w', 'Display information about users currently logged in', 'User Management', 'w -h'),
('users', 'Display a list of users currently logged in', 'User Management', 'users'),
('who', 'Display a list of users currently logged in', 'User Management', 'who -a'),
('ac', 'Display statistics about connect time', 'User Management', 'ac -p'),
('lastcomm', 'Display information about previously executed commands', 'User Management', 'lastcomm -u newuser'),
('aureport', 'Generate audit reports', 'User Management', 'aureport --start today'),
('auditctl', 'Control the auditing system', 'User Management', 'auditctl -w /etc/passwd -p wa'),
('auditd', 'The audit daemon', 'User Management', 'auditd -f')
ON CONFLICT (command_name) DO NOTHING;
