-- Seed file for 'linux_commands' table (500+ commands)
-- Run this in the Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.linux_commands (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    command_name TEXT NOT NULL,
    description TEXT NOT NULL,
    example_usage TEXT NOT NULL,
    category TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Optional: Enable RLS
ALTER TABLE public.linux_commands ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on linux_commands" ON public.linux_commands;
CREATE POLICY "Allow public read access on linux_commands" ON public.linux_commands FOR SELECT USING (true);

-- Clear existing data if you want a fresh start
TRUNCATE TABLE public.linux_commands;

INSERT INTO public.linux_commands (category, command_name, description, example_usage) VALUES

-- === 1. GIT (50 Commands) ===
('Git', 'git init', 'Initialize a new Git repository', 'git init'),
('Git', 'git clone', 'Clone an existing repository', 'git clone https://github.com/user/repo.git'),
('Git', 'git status', 'Check the status of the working tree', 'git status'),
('Git', 'git add .', 'Stage all changes in the directory', 'git add .'),
('Git', 'git add -p', 'Stage changes interactively (patch mode)', 'git add -p'),
('Git', 'git add -u', 'Stage modified and deleted files only', 'git add -u'),
('Git', 'git commit', 'Commit staged changes', 'git commit -m "Commit message"'),
('Git', 'git commit --amend', 'Amend the previous commit', 'git commit --amend -m "New message"'),
('Git', 'git push', 'Push local commits to remote', 'git push origin main'),
('Git', 'git push -f', 'Force push local commits to remote (use with caution)', 'git push -f origin main'),
('Git', 'git push -u', 'Push and set upstream tracking', 'git push -u origin feature'),
('Git', 'git pull', 'Fetch and merge from remote', 'git pull origin main'),
('Git', 'git pull --rebase', 'Fetch and rebase from remote', 'git pull --rebase origin main'),
('Git', 'git fetch', 'Download objects and refs from another repository', 'git fetch origin'),
('Git', 'git fetch --prune', 'Fetch and remove remote-tracking references that no longer exist', 'git fetch -p'),
('Git', 'git branch', 'List branches', 'git branch'),
('Git', 'git branch -a', 'List all local and remote branches', 'git branch -a'),
('Git', 'git branch -d', 'Delete a local branch', 'git branch -d feature'),
('Git', 'git branch -D', 'Force delete a local branch', 'git branch -D feature'),
('Git', 'git checkout', 'Switch to a branch', 'git checkout main'),
('Git', 'git checkout -b', 'Create and switch to a new branch', 'git checkout -b feature'),
('Git', 'git switch', 'Switch branches (modern alternative to checkout)', 'git switch main'),
('Git', 'git switch -c', 'Create and switch to a new branch', 'git switch -c feature'),
('Git', 'git merge', 'Merge a branch into the current branch', 'git merge feature'),
('Git', 'git merge --no-ff', 'Merge a branch without fast-forwarding', 'git merge --no-ff feature'),
('Git', 'git merge --abort', 'Abort a conflicted merge', 'git merge --abort'),
('Git', 'git rebase', 'Rebase current branch onto another', 'git rebase main'),
('Git', 'git rebase -i', 'Start an interactive rebase', 'git rebase -i HEAD~3'),
('Git', 'git rebase --continue', 'Continue a rebase after resolving conflicts', 'git rebase --continue'),
('Git', 'git rebase --abort', 'Abort a rebase', 'git rebase --abort'),
('Git', 'git log', 'Show commit logs', 'git log'),
('Git', 'git log --oneline', 'Show logs compactly', 'git log --oneline'),
('Git', 'git log --graph', 'Show logs with a branching graph', 'git log --graph --oneline --all'),
('Git', 'git reflog', 'Show a record of all local repository updates', 'git reflog'),
('Git', 'git diff', 'Show changes between commits, commit and working tree, etc', 'git diff'),
('Git', 'git diff --staged', 'Show changes that are staged for commit', 'git diff --staged'),
('Git', 'git stash', 'Stash working directory changes', 'git stash'),
('Git', 'git stash pop', 'Apply and remove the most recent stash', 'git stash pop'),
('Git', 'git stash apply', 'Apply the most recent stash without removing it', 'git stash apply'),
('Git', 'git stash list', 'List all stashes', 'git stash list'),
('Git', 'git stash drop', 'Remove a specific stash', 'git stash drop stash@{0}'),
('Git', 'git reset', 'Unstage files but keep modifications', 'git reset HEAD file.txt'),
('Git', 'git reset --soft', 'Undo commit, keep files staged', 'git reset --soft HEAD~1'),
('Git', 'git reset --hard', 'Undo commit and discard all modifications', 'git reset --hard HEAD~1'),
('Git', 'git revert', 'Create a new commit that undoes changes of a previous commit', 'git revert <commit_hash>'),
('Git', 'git cherry-pick', 'Apply the changes introduced by an existing commit', 'git cherry-pick <commit_hash>'),
('Git', 'git tag', 'List tags', 'git tag'),
('Git', 'git tag -a', 'Create an annotated tag', 'git tag -a v1.0 -m "Version 1.0"'),
('Git', 'git push --tags', 'Push all tags to remote', 'git push --tags'),
('Git', 'git remote -v', 'Show remote URLs', 'git remote -v'),
('Git', 'git remote add', 'Add a new remote repository', 'git remote add origin <url>'),
('Git', 'git rm', 'Remove files from the working tree and from the index', 'git rm file.txt'),

-- === 2. DOCKER (50 Commands) ===
('Docker', 'docker run', 'Run a command in a new container', 'docker run -d -p 80:80 nginx'),
('Docker', 'docker run -it', 'Run an interactive shell in a container', 'docker run -it ubuntu bash'),
('Docker', 'docker run --name', 'Assign a name to the container', 'docker run --name web -d nginx'),
('Docker', 'docker run -v', 'Bind mount a volume', 'docker run -v /host:/container nginx'),
('Docker', 'docker run -e', 'Set environment variables', 'docker run -e MYSQL_ROOT_PASSWORD=pass mysql'),
('Docker', 'docker ps', 'List running containers', 'docker ps'),
('Docker', 'docker ps -a', 'List all containers (running and stopped)', 'docker ps -a'),
('Docker', 'docker ps -q', 'List container IDs only', 'docker ps -q'),
('Docker', 'docker stop', 'Stop a running container', 'docker stop <container_id>'),
('Docker', 'docker start', 'Start a stopped container', 'docker start <container_id>'),
('Docker', 'docker restart', 'Restart a container', 'docker restart <container_id>'),
('Docker', 'docker kill', 'Kill a running container immediately', 'docker kill <container_id>'),
('Docker', 'docker rm', 'Remove a stopped container', 'docker rm <container_id>'),
('Docker', 'docker rm -f', 'Force remove a running container', 'docker rm -f <container_id>'),
('Docker', 'docker rm $(docker ps -aq)', 'Remove all stopped containers', 'docker rm $(docker ps -aq)'),
('Docker', 'docker images', 'List downloaded images', 'docker images'),
('Docker', 'docker rmi', 'Remove an image', 'docker rmi <image_id>'),
('Docker', 'docker pull', 'Download an image from a registry', 'docker pull ubuntu:20.04'),
('Docker', 'docker push', 'Upload an image to a registry', 'docker push myrepo/myapp:latest'),
('Docker', 'docker build', 'Build an image from a Dockerfile', 'docker build -t myapp:1.0 .'),
('Docker', 'docker build --no-cache', 'Build an image without using the cache', 'docker build --no-cache -t myapp .'),
('Docker', 'docker exec', 'Run a command in a running container', 'docker exec -it <container_id> sh'),
('Docker', 'docker logs', 'Fetch the logs of a container', 'docker logs <container_id>'),
('Docker', 'docker logs -f', 'Follow log output', 'docker logs -f <container_id>'),
('Docker', 'docker inspect', 'Return low-level information on Docker objects', 'docker inspect <container_id>'),
('Docker', 'docker top', 'Display the running processes of a container', 'docker top <container_id>'),
('Docker', 'docker stats', 'Display a live stream of container resource usage statistics', 'docker stats'),
('Docker', 'docker cp', 'Copy files/folders between a container and the local filesystem', 'docker cp <container_id>:/file/path /local/path'),
('Docker', 'docker network ls', 'List networks', 'docker network ls'),
('Docker', 'docker network create', 'Create a network', 'docker network create my_network'),
('Docker', 'docker network connect', 'Connect a container to a network', 'docker network connect my_network <container_id>'),
('Docker', 'docker network disconnect', 'Disconnect a container from a network', 'docker network disconnect my_network <container_id>'),
('Docker', 'docker volume ls', 'List volumes', 'docker volume ls'),
('Docker', 'docker volume create', 'Create a volume', 'docker volume create my_volume'),
('Docker', 'docker volume rm', 'Remove a volume', 'docker volume rm my_volume'),
('Docker', 'docker system prune', 'Remove unused data (containers, networks, images)', 'docker system prune -a'),
('Docker', 'docker login', 'Log in to a Docker registry', 'docker login'),
('Docker', 'docker logout', 'Log out from a Docker registry', 'docker logout'),
('Docker', 'docker commit', 'Create a new image from a container''s changes', 'docker commit <container_id> mynewimage'),
('Docker', 'docker tag', 'Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE', 'docker tag myapp:latest myrepo/myapp:v1'),
('Docker', 'docker save', 'Save one or more images to a tar archive', 'docker save -o image.tar ubuntu'),
('Docker', 'docker load', 'Load an image from a tar archive or STDIN', 'docker load -i image.tar'),
('Docker', 'docker-compose up', 'Builds, (re)creates, starts, and attaches to containers for a service', 'docker-compose up'),
('Docker', 'docker-compose up -d', 'Start services in detached mode', 'docker-compose up -d'),
('Docker', 'docker-compose down', 'Stop and remove containers, networks, images, and volumes', 'docker-compose down'),
('Docker', 'docker-compose stop', 'Stop services', 'docker-compose stop'),
('Docker', 'docker-compose build', 'Build or rebuild services', 'docker-compose build'),
('Docker', 'docker-compose logs', 'View output from containers', 'docker-compose logs -f'),
('Docker', 'docker-compose ps', 'List containers in compose project', 'docker-compose ps'),
('Docker', 'docker-compose exec', 'Execute a command in a running compose container', 'docker-compose exec web sh'),

-- === 3. VIM (50 Commands) ===
('Vim', 'i', 'Enter Insert mode before the cursor', 'i'),
('Vim', 'I', 'Enter Insert mode at the beginning of the line', 'I'),
('Vim', 'a', 'Enter Insert mode after the cursor', 'a'),
('Vim', 'A', 'Enter Insert mode at the end of the line', 'A'),
('Vim', 'o', 'Open a new line below the current line and enter Insert mode', 'o'),
('Vim', 'O', 'Open a new line above the current line and enter Insert mode', 'O'),
('Vim', 'Esc', 'Exit Insert mode or command mode', '<Esc>'),
('Vim', ':w', 'Write (save) the file', ':w'),
('Vim', ':w filename', 'Save file as filename', ':w filename'),
('Vim', ':q', 'Quit Vim', ':q'),
('Vim', ':wq', 'Write and quit', ':wq'),
('Vim', ':x', 'Write and quit (same as :wq)', ':x'),
('Vim', 'ZZ', 'Write and quit (shortcut)', 'ZZ'),
('Vim', ':q!', 'Quit without saving changes (force quit)', ':q!'),
('Vim', 'h', 'Move cursor left', 'h'),
('Vim', 'j', 'Move cursor down', 'j'),
('Vim', 'k', 'Move cursor up', 'k'),
('Vim', 'l', 'Move cursor right', 'l'),
('Vim', 'w', 'Move forward to the beginning of a word', 'w'),
('Vim', 'e', 'Move forward to the end of a word', 'e'),
('Vim', 'b', 'Move backward to the beginning of a word', 'b'),
('Vim', '0', 'Move to the beginning of the line', '0'),
('Vim', '^', 'Move to the first non-blank character of the line', '^'),
('Vim', '$', 'Move to the end of the line', '$'),
('Vim', 'gg', 'Move to the first line of the file', 'gg'),
('Vim', 'G', 'Move to the last line of the file', 'G'),
('Vim', 'nG', 'Move to line number n', '50G'),
('Vim', 'x', 'Delete the character under the cursor', 'x'),
('Vim', 'X', 'Delete the character before the cursor', 'X'),
('Vim', 'dd', 'Delete (cut) the current line', 'dd'),
('Vim', 'ndd', 'Delete n lines', '3dd'),
('Vim', 'dw', 'Delete from cursor to the beginning of the next word', 'dw'),
('Vim', 'd$', 'Delete from cursor to the end of the line', 'd$'),
('Vim', 'yy', 'Yank (copy) the current line', 'yy'),
('Vim', 'nyy', 'Yank n lines', '3yy'),
('Vim', 'p', 'Put (paste) the deleted or yanked text after the cursor', 'p'),
('Vim', 'P', 'Put (paste) the deleted or yanked text before the cursor', 'P'),
('Vim', 'u', 'Undo the last change', 'u'),
('Vim', 'Ctrl+r', 'Redo the last undone change', '<C-r>'),
('Vim', '.', 'Repeat the last command', '.'),
('Vim', '/pattern', 'Search forward for pattern', '/foo'),
('Vim', '?pattern', 'Search backward for pattern', '?foo'),
('Vim', 'n', 'Repeat the last search in the same direction', 'n'),
('Vim', 'N', 'Repeat the last search in the opposite direction', 'N'),
('Vim', ':%s/old/new/g', 'Replace all occurrences of old with new in the entire file', ':%s/foo/bar/g'),
('Vim', ':%s/old/new/gc', 'Replace with confirmation', ':%s/foo/bar/gc'),
('Vim', 'v', 'Enter visual mode (character-wise)', 'v'),
('Vim', 'V', 'Enter visual line mode', 'V'),
('Vim', 'Ctrl+v', 'Enter visual block mode', '<C-v>'),
('Vim', '>> (indent)', 'Indent current line right', '>>'),
('Vim', '<<', 'Indent current line left', '<<'),

-- === 4. BASH SCRIPTING (50 Commands) ===
('Bash Scripting', '#!/bin/bash', 'Shebang line to specify the script interpreter', '#!/bin/bash'),
('Bash Scripting', '#', 'Comment line', '# This is a comment'),
('Bash Scripting', 'var=value', 'Assign value to a variable (no spaces around =)', 'name="John"'),
('Bash Scripting', '$var', 'Access the value of a variable', 'echo $name'),
('Bash Scripting', 'read', 'Read user input into a variable', 'read -p "Enter your name: " name'),
('Bash Scripting', '$1, $2', 'Access positional parameters (arguments passed to script)', 'echo "First argument: $1"'),
('Bash Scripting', '$0', 'Name of the bash script', 'echo "Script name: $0"'),
('Bash Scripting', '$@', 'All positional parameters as separate words', 'for arg in "$@"; do echo $arg; done'),
('Bash Scripting', '$#', 'Number of positional parameters', 'echo "Total args: $#"'),
('Bash Scripting', '$?', 'Exit status of the last executed command', 'echo "Exit code: $?"'),
('Bash Scripting', '$$', 'Process ID (PID) of the current shell', 'echo "My PID is $$"'),
('Bash Scripting', 'if [ condition ]; then', 'If statement', 'if [ $a -gt 10 ]; then echo "greater"; fi'),
('Bash Scripting', 'elif [ condition ]; then', 'Else-if statement', 'elif [ $a -eq 10 ]; then echo "equal"; fi'),
('Bash Scripting', 'else', 'Else statement', 'else echo "less"; fi'),
('Bash Scripting', '-eq, -ne', 'Numeric comparison: equal, not equal', '[ $a -eq $b ]'),
('Bash Scripting', '-gt, -lt', 'Numeric comparison: greater than, less than', '[ $a -gt $b ]'),
('Bash Scripting', '-ge, -le', 'Numeric comparison: greater or equal, less or equal', '[ $a -ge $b ]'),
('Bash Scripting', '==, !=', 'String comparison: equal, not equal', '[ "$str1" == "$str2" ]'),
('Bash Scripting', '-z', 'Check if string is empty (length zero)', '[ -z "$str" ]'),
('Bash Scripting', '-n', 'Check if string is not empty', '[ -n "$str" ]'),
('Bash Scripting', '-f', 'Check if file exists and is a regular file', '[ -f "/path/to/file" ]'),
('Bash Scripting', '-d', 'Check if directory exists', '[ -d "/path/to/dir" ]'),
('Bash Scripting', 'for i in list; do', 'For loop iterating over a list', 'for i in 1 2 3; do echo $i; done'),
('Bash Scripting', 'for i in {start..end}; do', 'For loop iterating over a range', 'for i in {1..10}; do echo $i; done'),
('Bash Scripting', 'while [ condition ]; do', 'While loop', 'while [ $i -lt 10 ]; do echo $i; ((i++)); done'),
('Bash Scripting', 'until [ condition ]; do', 'Until loop (runs until condition becomes true)', 'until [ $i -ge 10 ]; do echo $i; ((i++)); done'),
('Bash Scripting', 'case $var in', 'Case (switch) statement', 'case $1 in start) echo "Starting";; stop) echo "Stopping";; esac'),
('Bash Scripting', 'function_name() {}', 'Define a function', 'greet() { echo "Hello $1"; }'),
('Bash Scripting', 'local var=value', 'Define a local variable within a function', 'local result="success"'),
('Bash Scripting', 'return', 'Return a status code from a function', 'return 0'),
('Bash Scripting', '$(command)', 'Command substitution (execute command and return output)', 'date_str=$(date)'),
('Bash Scripting', '`command`', 'Older syntax for command substitution', 'date_str=`date`'),
('Bash Scripting', '(( math_expr ))', 'Arithmetic evaluation', '(( sum = a + b ))'),
('Bash Scripting', '$(( math_expr ))', 'Arithmetic expansion (returns result)', 'echo $(( 5 + 3 ))'),
('Bash Scripting', '>', 'Redirect standard output to a file (overwrite)', 'echo "text" > file.txt'),
('Bash Scripting', '>> (append)', 'Redirect standard output to a file (append)', 'echo "more text" >> file.txt'),
('Bash Scripting', '<', 'Redirect standard input from a file', 'sort < file.txt'),
('Bash Scripting', '2>', 'Redirect standard error to a file', 'ls non_existent_file 2> error.log'),
('Bash Scripting', '2>&1', 'Redirect standard error to standard output', 'command > output.log 2>&1'),
('Bash Scripting', '&>', 'Redirect both stdout and stderr to a file', 'command &> all_output.log'),
('Bash Scripting', '|', 'Pipe output of one command to input of another', 'ls -l | grep "txt"'),
('Bash Scripting', '&&', 'Logical AND: run command2 only if command1 succeeds', 'make && make install'),
('Bash Scripting', '||', 'Logical OR: run command2 only if command1 fails', 'grep "foo" file.txt || echo "Not found"'),
('Bash Scripting', 'set -e', 'Exit script immediately if a command exits with a non-zero status', 'set -e'),
('Bash Scripting', 'set -u', 'Treat unset variables as an error when substituting', 'set -u'),
('Bash Scripting', 'set -x', 'Print commands and their arguments as they are executed (debugging)', 'set -x'),
('Bash Scripting', 'set -o pipefail', 'Pipeline returns failure if any command within it fails', 'set -o pipefail'),
('Bash Scripting', 'trap', 'Execute a command when the script receives a signal', 'trap "echo EXITING; exit" SIGINT'),
('Bash Scripting', 'shift', 'Shift positional parameters to the left ($2 becomes $1)', 'shift'),
('Bash Scripting', 'export', 'Export a variable to the environment of child processes', 'export API_KEY="12345"'),

-- === 5. LINUX COMMANDS (50 Commands) ===
('Linux Commands', 'ls', 'List directory contents', 'ls -lah'),
('Linux Commands', 'cd', 'Change directory', 'cd /var/log'),
('Linux Commands', 'pwd', 'Print working directory', 'pwd'),
('Linux Commands', 'mkdir', 'Make a new directory', 'mkdir -p /path/to/dir'),
('Linux Commands', 'rmdir', 'Remove empty directory', 'rmdir mydir'),
('Linux Commands', 'rm', 'Remove files or directories', 'rm -rf mydir/'),
('Linux Commands', 'cp', 'Copy files or directories', 'cp -r src/ dest/'),
('Linux Commands', 'mv', 'Move or rename files or directories', 'mv oldname newname'),
('Linux Commands', 'touch', 'Create an empty file or update timestamps', 'touch file.txt'),
('Linux Commands', 'cat', 'Concatenate and print files', 'cat file.txt'),
('Linux Commands', 'tac', 'Print files in reverse order (last line first)', 'tac file.txt'),
('Linux Commands', 'less', 'View file contents page by page', 'less large_log.txt'),
('Linux Commands', 'more', 'View file contents page by page (older than less)', 'more file.txt'),
('Linux Commands', 'head', 'Output the first lines of a file', 'head -n 20 file.txt'),
('Linux Commands', 'tail', 'Output the last lines of a file', 'tail -n 20 file.txt'),
('Linux Commands', 'tail -f', 'Follow appended data as the file grows', 'tail -f /var/log/syslog'),
('Linux Commands', 'find', 'Search for files in a directory hierarchy', 'find / -name "*.conf"'),
('Linux Commands', 'locate', 'Find files by name (uses a pre-built database)', 'locate myconfig.conf'),
('Linux Commands', 'which', 'Locate a command', 'which node'),
('Linux Commands', 'whereis', 'Locate the binary, source, and manual page files for a command', 'whereis python'),
('Linux Commands', 'type', 'Describe a command (alias, built-in, file)', 'type ls'),
('Linux Commands', 'chmod', 'Change file permissions', 'chmod 755 script.sh'),
('Linux Commands', 'chown', 'Change file owner and group', 'chown www-data:www-data html/'),
('Linux Commands', 'df', 'Report file system disk space usage', 'df -h'),
('Linux Commands', 'du', 'Estimate file space usage', 'du -sh /var/log/*'),
('Linux Commands', 'free', 'Display amount of free and used memory', 'free -m'),
('Linux Commands', 'top', 'Display Linux tasks (dynamic real-time view)', 'top'),
('Linux Commands', 'htop', 'Interactive process viewer (better than top)', 'htop'),
('Linux Commands', 'ps', 'Report a snapshot of the current processes', 'ps aux'),
('Linux Commands', 'kill', 'Send a signal to a process (terminate)', 'kill 1234'),
('Linux Commands', 'killall', 'Kill processes by name', 'killall nginx'),
('Linux Commands', 'pkill', 'Signal processes based on name and other attributes', 'pkill -f python'),
('Linux Commands', 'bg', 'Send a job to the background', 'bg %1'),
('Linux Commands', 'fg', 'Bring a job to the foreground', 'fg %1'),
('Linux Commands', 'jobs', 'List active jobs', 'jobs'),
('Linux Commands', 'nohup', 'Run a command immune to hangups, with output to a non-tty', 'nohup script.sh &'),
('Linux Commands', 'history', 'Display the command history list', 'history'),
('Linux Commands', 'clear', 'Clear the terminal screen', 'clear'),
('Linux Commands', 'echo', 'Display a line of text', 'echo "Hello World"'),
('Linux Commands', 'printf', 'Format and print data', 'printf "%s\n" "Hello"'),
('Linux Commands', 'date', 'Print or set the system date and time', 'date'),
('Linux Commands', 'cal', 'Display a calendar', 'cal'),
('Linux Commands', 'uptime', 'Tell how long the system has been running', 'uptime'),
('Linux Commands', 'uname', 'Print system information', 'uname -a'),
('Linux Commands', 'whoami', 'Print effective userid', 'whoami'),
('Linux Commands', 'id', 'Print real and effective user and group IDs', 'id'),
('Linux Commands', 'groups', 'Print the groups a user is in', 'groups user'),
('Linux Commands', 'useradd', 'Create a new user or update default new user information', 'useradd -m newuser'),
('Linux Commands', 'usermod', 'Modify a user account', 'usermod -aG sudo newuser'),
('Linux Commands', 'passwd', 'Change user password', 'passwd newuser'),
('Linux Commands', 'tar', 'Archive utility (create, extract, list)', 'tar -czvf archive.tar.gz folder/'),

-- === 6. NETWORKING (50 Commands) ===
('Networking', 'ping', 'Send ICMP ECHO_REQUEST to network hosts', 'ping 8.8.8.8'),
('Networking', 'ip a', 'Show IP addresses and network interfaces', 'ip a'),
('Networking', 'ip link', 'Network device configuration', 'ip link show'),
('Networking', 'ip route', 'Show or manipulate the IP routing table', 'ip route show'),
('Networking', 'ifconfig', 'Configure a network interface (deprecated, use ip)', 'ifconfig eth0'),
('Networking', 'netstat -tuln', 'Print listening TCP/UDP ports', 'netstat -tuln'),
('Networking', 'ss -tuln', 'Dump socket statistics (modern netstat)', 'ss -tuln'),
('Networking', 'traceroute', 'Print the route packets trace to network host', 'traceroute google.com'),
('Networking', 'tracepath', 'Traces path to a network host discovering MTU along this path', 'tracepath google.com'),
('Networking', 'mtr', 'Network diagnostic tool (combines ping and traceroute)', 'mtr google.com'),
('Networking', 'nslookup', 'Query Internet name servers interactively', 'nslookup example.com'),
('Networking', 'dig', 'DNS lookup utility', 'dig example.com A'),
('Networking', 'host', 'DNS lookup utility', 'host example.com'),
('Networking', 'whois', 'Client for the whois directory service', 'whois example.com'),
('Networking', 'arp -a', 'Display the ARP cache', 'arp -a'),
('Networking', 'curl', 'Transfer data from or to a server', 'curl https://api.example.com'),
('Networking', 'curl -I', 'Fetch only the HTTP headers', 'curl -I https://example.com'),
('Networking', 'curl -O', 'Download a file and save it with the remote name', 'curl -O https://example.com/file.zip'),
('Networking', 'curl -X POST', 'Make an HTTP POST request', 'curl -X POST -d "key=val" http://api.com'),
('Networking', 'wget', 'Non-interactive network downloader', 'wget https://example.com/file.zip'),
('Networking', 'wget -c', 'Resume an interrupted download', 'wget -c https://example.com/file.zip'),
('Networking', 'nmap', 'Network exploration tool and security / port scanner', 'nmap -sV 192.168.1.1'),
('Networking', 'nmap -p', 'Scan specific ports', 'nmap -p 22,80,443 192.168.1.1'),
('Networking', 'tcpdump', 'Dump traffic on a network', 'tcpdump -i eth0'),
('Networking', 'tcpdump port 80', 'Capture traffic on a specific port', 'tcpdump port 80'),
('Networking', 'nc (netcat)', 'Arbitrary TCP and UDP connections and listens', 'nc -vz 192.168.1.1 80'),
('Networking', 'nc -l', 'Listen for an incoming connection', 'nc -l -p 8080'),
('Networking', 'telnet', 'User interface to the TELNET protocol', 'telnet 192.168.1.1 80'),
('Networking', 'iptables -L', 'List all iptables rules', 'iptables -L -n -v'),
('Networking', 'iptables -A', 'Append a rule to a chain', 'iptables -A INPUT -p tcp --dport 22 -j ACCEPT'),
('Networking', 'ufw status', 'Check the status of Uncomplicated Firewall', 'ufw status verbose'),
('Networking', 'ufw allow', 'Allow specific port in UFW', 'ufw allow 80/tcp'),
('Networking', 'ufw deny', 'Deny specific port in UFW', 'ufw deny 23/tcp'),
('Networking', 'firewall-cmd --list-all', 'List all firewallD settings', 'firewall-cmd --list-all'),
('Networking', 'firewall-cmd --add-port', 'Add port to firewalld', 'firewall-cmd --add-port=80/tcp --permanent'),
('Networking', 'hostname', 'Show or set the system''s host name', 'hostname'),
('Networking', 'hostnamectl', 'Control the system hostname', 'hostnamectl set-hostname new-name'),
('Networking', 'route -n', 'Show the IP routing table', 'route -n'),
('Networking', 'iwconfig', 'Configure a wireless network interface', 'iwconfig wlan0'),
('Networking', 'nmcli', 'Command-line tool for controlling NetworkManager', 'nmcli dev wifi list'),
('Networking', 'nmcli connection up', 'Activate a network connection', 'nmcli connection up id "My Wi-Fi"'),
('Networking', 'iperf3', 'Perform network throughput tests', 'iperf3 -c 192.168.1.1'),
('Networking', 'iperf3 -s', 'Run iperf3 in server mode', 'iperf3 -s'),
('Networking', 'socat', 'Multipurpose relay (SOcket CAT)', 'socat TCP-LISTEN:8080,fork TCP:192.168.1.2:80'),
('Networking', 'iftop', 'Display bandwidth usage on an interface by host', 'iftop -i eth0'),
('Networking', 'nload', 'Visual representation of incoming and outgoing traffic', 'nload eth0'),
('Networking', 'vnstat', 'Console-based network traffic monitor', 'vnstat -l'),
('Networking', 'dhclient', 'Dynamic Host Configuration Protocol Client', 'dhclient eth0'),
('Networking', 'resolv.conf', 'File containing DNS resolution configuration', 'cat /etc/resolv.conf'),
('Networking', 'hosts', 'Static table lookup for hostnames', 'cat /etc/hosts'),

-- === 7. KUBERNETES (50 Commands) ===
('Kubernetes', 'kubectl version', 'Print the client and server version information', 'kubectl version --short'),
('Kubernetes', 'kubectl cluster-info', 'Display cluster info', 'kubectl cluster-info'),
('Kubernetes', 'kubectl get pods', 'List pods in the current namespace', 'kubectl get pods'),
('Kubernetes', 'kubectl get pods -A', 'List pods in all namespaces', 'kubectl get pods -A'),
('Kubernetes', 'kubectl get pods -o wide', 'List pods with more details (IP, Node)', 'kubectl get pods -o wide'),
('Kubernetes', 'kubectl get deployments', 'List deployments', 'kubectl get deployments'),
('Kubernetes', 'kubectl get services', 'List services', 'kubectl get svc'),
('Kubernetes', 'kubectl get nodes', 'List nodes in the cluster', 'kubectl get nodes'),
('Kubernetes', 'kubectl get namespaces', 'List all namespaces', 'kubectl get ns'),
('Kubernetes', 'kubectl describe pod', 'Show detailed info about a pod', 'kubectl describe pod <pod-name>'),
('Kubernetes', 'kubectl describe node', 'Show detailed info about a node', 'kubectl describe node <node-name>'),
('Kubernetes', 'kubectl apply -f', 'Apply a configuration file', 'kubectl apply -f config.yaml'),
('Kubernetes', 'kubectl create', 'Create a resource from file or stdin', 'kubectl create -f config.yaml'),
('Kubernetes', 'kubectl delete -f', 'Delete resources defined in a file', 'kubectl delete -f config.yaml'),
('Kubernetes', 'kubectl delete pod', 'Delete a specific pod', 'kubectl delete pod <pod-name>'),
('Kubernetes', 'kubectl delete deployment', 'Delete a deployment', 'kubectl delete deployment <deployment-name>'),
('Kubernetes', 'kubectl logs', 'Print the logs for a container in a pod', 'kubectl logs <pod-name>'),
('Kubernetes', 'kubectl logs -f', 'Stream logs from a pod', 'kubectl logs -f <pod-name>'),
('Kubernetes', 'kubectl logs -c', 'Print logs for a specific container in a multi-container pod', 'kubectl logs <pod-name> -c <container-name>'),
('Kubernetes', 'kubectl exec', 'Execute a command in a container', 'kubectl exec -it <pod-name> -- /bin/sh'),
('Kubernetes', 'kubectl port-forward', 'Forward local ports to a pod or service', 'kubectl port-forward svc/<service-name> 8080:80'),
('Kubernetes', 'kubectl scale', 'Scale a deployment, ReplicaSet, or StatefulSet', 'kubectl scale deployment <name> --replicas=3'),
('Kubernetes', 'kubectl rollout status', 'Show rollout status', 'kubectl rollout status deployment/<name>'),
('Kubernetes', 'kubectl rollout history', 'View rollout history', 'kubectl rollout history deployment/<name>'),
('Kubernetes', 'kubectl rollout undo', 'Rollback to a previous rollout', 'kubectl rollout undo deployment/<name>'),
('Kubernetes', 'kubectl set image', 'Update image of a deployment', 'kubectl set image deployment/<name> container=new-image:v2'),
('Kubernetes', 'kubectl edit', 'Edit a resource on the server', 'kubectl edit deployment/<name>'),
('Kubernetes', 'kubectl label', 'Update the labels on a resource', 'kubectl label pods <pod-name> new-label=awesome'),
('Kubernetes', 'kubectl annotate', 'Update the annotations on a resource', 'kubectl annotate pods <pod-name> icon-url=http://...'),
('Kubernetes', 'kubectl get events', 'List events in the current namespace', 'kubectl get events --sort-by=.metadata.creationTimestamp'),
('Kubernetes', 'kubectl top node', 'Display Resource (CPU/Memory) usage of nodes', 'kubectl top node'),
('Kubernetes', 'kubectl top pod', 'Display Resource (CPU/Memory) usage of pods', 'kubectl top pod'),
('Kubernetes', 'kubectl config view', 'Display merged kubeconfig settings', 'kubectl config view'),
('Kubernetes', 'kubectl config get-contexts', 'Describe one or many contexts', 'kubectl config get-contexts'),
('Kubernetes', 'kubectl config use-context', 'Set the current-context in a kubeconfig file', 'kubectl config use-context <context-name>'),
('Kubernetes', 'kubectl config set-context', 'Set a context entry in kubeconfig', 'kubectl config set-context --current --namespace=<namespace>'),
('Kubernetes', 'kubectl get secrets', 'List secrets', 'kubectl get secrets'),
('Kubernetes', 'kubectl get configmaps', 'List configmaps', 'kubectl get cm'),
('Kubernetes', 'kubectl create secret', 'Create a secret', 'kubectl create secret generic my-secret --from-literal=key=value'),
('Kubernetes', 'kubectl create configmap', 'Create a configmap', 'kubectl create configmap my-config --from-file=config.properties'),
('Kubernetes', 'kubectl auth can-i', 'Check authorization', 'kubectl auth can-i create deployments --namespace dev'),
('Kubernetes', 'kubectl taint node', 'Update the taints on one or more nodes', 'kubectl taint nodes <node-name> key=value:NoSchedule'),
('Kubernetes', 'kubectl cordon', 'Mark node as unschedulable', 'kubectl cordon <node-name>'),
('Kubernetes', 'kubectl uncordon', 'Mark node as schedulable', 'kubectl uncordon <node-name>'),
('Kubernetes', 'kubectl drain', 'Drain node in preparation for maintenance', 'kubectl drain <node-name> --ignore-daemonsets'),
('Kubernetes', 'kubectl cp', 'Copy files and directories to and from containers', 'kubectl cp /local/path <namespace>/<pod-name>:/container/path'),
('Kubernetes', 'kubectl diff', 'Diff file or stdin against live configuration', 'kubectl diff -f config.yaml'),
('Kubernetes', 'kubectl explain', 'Get documentation of various resources', 'kubectl explain pods.spec.containers'),
('Kubernetes', 'kubectl get ing', 'List ingress resources', 'kubectl get ing'),
('Kubernetes', 'kubectl get hpa', 'List HorizontalPodAutoscalers', 'kubectl get hpa'),

-- === 8. SSH (50 Commands) ===
('SSH', 'ssh', 'Connect to a remote server', 'ssh user@hostname'),
('SSH', 'ssh -p', 'Connect using a specific port', 'ssh -p 2222 user@hostname'),
('SSH', 'ssh -i', 'Connect using a specific private key', 'ssh -i ~/.ssh/id_rsa user@hostname'),
('SSH', 'ssh -v', 'Verbose mode (helpful for debugging connections)', 'ssh -v user@hostname'),
('SSH', 'ssh -vvv', 'Maximum verbosity for deep debugging', 'ssh -vvv user@hostname'),
('SSH', 'ssh -X', 'Enable X11 forwarding (GUI over SSH)', 'ssh -X user@hostname'),
('SSH', 'ssh -Y', 'Enable trusted X11 forwarding', 'ssh -Y user@hostname'),
('SSH', 'ssh -C', 'Enable data compression', 'ssh -C user@hostname'),
('SSH', 'ssh -L', 'Local port forwarding (tunneling)', 'ssh -L 8080:localhost:80 user@hostname'),
('SSH', 'ssh -R', 'Remote port forwarding', 'ssh -R 8080:localhost:80 user@hostname'),
('SSH', 'ssh -D', 'Dynamic port forwarding (SOCKS proxy)', 'ssh -D 8080 user@hostname'),
('SSH', 'ssh -N', 'Do not execute a remote command (useful for forwarding ports)', 'ssh -N -L 8080:localhost:80 user@hostname'),
('SSH', 'ssh -f', 'Run SSH in the background (useful with port forwarding)', 'ssh -f -N -L 8080:localhost:80 user@hostname'),
('SSH', 'ssh -t', 'Force pseudo-terminal allocation (useful for interactive commands)', 'ssh -t user@hostname "sudo htop"'),
('SSH', 'ssh -J', 'Connect via a jump host', 'ssh -J jumpuser@jumphost user@targethost'),
('SSH', 'ssh-keygen', 'Generate a new SSH key pair', 'ssh-keygen -t ed25519 -C "your_email@example.com"'),
('SSH', 'ssh-keygen -R', 'Remove a host from the known_hosts file', 'ssh-keygen -R hostname'),
('SSH', 'ssh-keygen -p', 'Change the passphrase of a private key', 'ssh-keygen -p -f ~/.ssh/id_rsa'),
('SSH', 'ssh-keygen -y', 'Read a private SSH key and print its public key', 'ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub'),
('SSH', 'ssh-copy-id', 'Copy public key to a remote server to enable passwordless login', 'ssh-copy-id user@hostname'),
('SSH', 'ssh-copy-id -i', 'Copy a specific public key to a remote server', 'ssh-copy-id -i ~/.ssh/mykey.pub user@hostname'),
('SSH', 'scp', 'Securely copy files to/from a remote server', 'scp file.txt user@hostname:/path/to/dest'),
('SSH', 'scp -r', 'Securely copy a directory recursively', 'scp -r /local/dir user@hostname:/remote/dir'),
('SSH', 'scp -P', 'Securely copy files using a specific port', 'scp -P 2222 file.txt user@hostname:/dest'),
('SSH', 'scp -i', 'Securely copy using a specific private key', 'scp -i ~/.ssh/id_rsa file.txt user@hostname:/dest'),
('SSH', 'sftp', 'Secure File Transfer Protocol interactive session', 'sftp user@hostname'),
('SSH', 'sftp -P', 'Connect SFTP on a specific port', 'sftp -P 2222 user@hostname'),
('SSH', 'eval $(ssh-agent)', 'Start the ssh-agent in the background', 'eval $(ssh-agent -s)'),
('SSH', 'ssh-add', 'Add private key identities to the authentication agent', 'ssh-add ~/.ssh/id_rsa'),
('SSH', 'ssh-add -l', 'List fingerprints of all identities currently represented by the agent', 'ssh-add -l'),
('SSH', 'ssh-add -D', 'Delete all identities from the agent', 'ssh-add -D'),
('SSH', '~/.ssh/config', 'The SSH client configuration file (not a command, but essential)', 'nano ~/.ssh/config'),
('SSH', 'Host alias', 'Define a connection alias in ~/.ssh/config', 'Host dev\n  HostName 10.0.0.5\n  User root'),
('SSH', '/etc/ssh/sshd_config', 'The SSH server configuration file', 'sudo nano /etc/ssh/sshd_config'),
('SSH', 'systemctl restart sshd', 'Restart the SSH service after config changes', 'sudo systemctl restart sshd'),
('SSH', 'ssh-keyscan', 'Gather ssh public keys from a remote host', 'ssh-keyscan github.com >> ~/.ssh/known_hosts'),
('SSH', 'ProxyJump', 'Config file directive to use a jump host', 'ProxyJump jumpuser@jumphost'),
('SSH', 'StrictHostKeyChecking no', 'Config directive to disable host key verification (insecure)', 'ssh -o StrictHostKeyChecking=no user@host'),
('SSH', 'PasswordAuthentication no', 'Server config to disable password logins (use keys only)', 'PasswordAuthentication no'),
('SSH', 'PermitRootLogin no', 'Server config to disable direct root login via SSH', 'PermitRootLogin no'),
('SSH', 'PubkeyAuthentication yes', 'Server config to enable public key logins', 'PubkeyAuthentication yes'),
('SSH', 'ClientAliveInterval', 'Server config to send keep-alive messages', 'ClientAliveInterval 60'),
('SSH', 'ServerAliveInterval', 'Client config to send keep-alive messages to prevent disconnects', 'ServerAliveInterval 60'),
('SSH', 'mosh', 'Mobile Shell - roaming and responsive alternative to SSH', 'mosh user@hostname'),
('SSH', 'sshd -t', 'Test the SSH daemon configuration for syntax errors', 'sudo sshd -t'),
('SSH', 'tail -f /var/log/auth.log', 'Monitor SSH login attempts (Debian/Ubuntu)', 'tail -f /var/log/auth.log'),
('SSH', 'tail -f /var/log/secure', 'Monitor SSH login attempts (RHEL/CentOS)', 'tail -f /var/log/secure'),
('SSH', 'fail2ban', 'Tool to ban IPs that show malicious signs like too many password failures', 'sudo systemctl status fail2ban'),
('SSH', 'sshpass', 'Non-interactive ssh password provider (not recommended for production)', 'sshpass -p "password" ssh user@host'),
('SSH', 'tmux via ssh', 'Attach to a persistent session on a remote server', 'ssh -t user@host "tmux attach || tmux new"'),

-- === 9. GREP & SED & AWK (50 Commands) ===
('Grep & Sed & Awk', 'grep "pattern" file', 'Search for a string in a file', 'grep "error" /var/log/syslog'),
('Grep & Sed & Awk', 'grep -i', 'Case-insensitive search', 'grep -i "ERROR" file.txt'),
('Grep & Sed & Awk', 'grep -v', 'Invert match (show lines that do NOT match)', 'grep -v "debug" file.txt'),
('Grep & Sed & Awk', 'grep -r', 'Search recursively in a directory', 'grep -r "TODO" ./src'),
('Grep & Sed & Awk', 'grep -n', 'Show line numbers with matches', 'grep -n "function" script.sh'),
('Grep & Sed & Awk', 'grep -l', 'Show only filenames containing the match', 'grep -l "API_KEY" *.env'),
('Grep & Sed & Awk', 'grep -c', 'Count the number of matching lines', 'grep -c "Failed" auth.log'),
('Grep & Sed & Awk', 'grep -w', 'Match whole words only', 'grep -w "is" file.txt'),
('Grep & Sed & Awk', 'grep -x', 'Match exact whole lines only', 'grep -x "localhost" hosts'),
('Grep & Sed & Awk', 'grep -E', 'Use Extended Regular Expressions (same as egrep)', 'grep -E "error|warning" file.txt'),
('Grep & Sed & Awk', 'grep -A n', 'Show n lines After the match', 'grep -A 3 "Exception" app.log'),
('Grep & Sed & Awk', 'grep -B n', 'Show n lines Before the match', 'grep -B 2 "Exception" app.log'),
('Grep & Sed & Awk', 'grep -C n', 'Show n lines of Context (before and after)', 'grep -C 3 "Exception" app.log'),
('Grep & Sed & Awk', 'grep -o', 'Show only the matching part of the line', 'grep -o "[0-9]*" numbers.txt'),
('Grep & Sed & Awk', 'pgrep', 'Search for processes by name', 'pgrep nginx'),
('Grep & Sed & Awk', 'sed ''s/old/new/''', 'Replace the first occurrence on each line', 'sed ''s/foo/bar/'' file.txt'),
('Grep & Sed & Awk', 'sed ''s/old/new/g''', 'Replace all occurrences on each line', 'sed ''s/foo/bar/g'' file.txt'),
('Grep & Sed & Awk', 'sed -i', 'Edit file in-place (save changes to the file)', 'sed -i ''s/false/true/g'' config.json'),
('Grep & Sed & Awk', 'sed -i.bak', 'Edit in-place but create a backup file', 'sed -i.bak ''s/foo/bar/'' file.txt'),
('Grep & Sed & Awk', 'sed ''Nd''', 'Delete the Nth line', 'sed ''5d'' file.txt'),
('Grep & Sed & Awk', 'sed ''$d''', 'Delete the last line', 'sed ''$d'' file.txt'),
('Grep & Sed & Awk', 'sed ''N,Md''', 'Delete lines from N to M', 'sed ''2,5d'' file.txt'),
('Grep & Sed & Awk', 'sed ''/pattern/d''', 'Delete lines matching a pattern', 'sed ''/debug/d'' file.txt'),
('Grep & Sed & Awk', 'sed -n ''p''', 'Print lines (useful with -n to suppress default output)', 'sed -n ''/error/p'' file.txt'),
('Grep & Sed & Awk', 'sed ''s/.*=//''', 'Remove everything before and including the first =', 'sed ''s/.*=//'' config.txt'),
('Grep & Sed & Awk', 'sed ''s/^[ \t]*//''', 'Remove leading whitespace', 'sed ''s/^[ \t]*//'' file.txt'),
('Grep & Sed & Awk', 'sed ''s/[ \t]*$//''', 'Remove trailing whitespace', 'sed ''s/[ \t]*$//'' file.txt'),
('Grep & Sed & Awk', 'sed ''/^$/d''', 'Remove blank lines', 'sed ''/^$/d'' file.txt'),
('Grep & Sed & Awk', 'sed ''a\text''', 'Append text after a line', 'sed ''/pattern/a\new line'' file.txt'),
('Grep & Sed & Awk', 'sed ''i\text''', 'Insert text before a line', 'sed ''/pattern/i\new line'' file.txt'),
('Grep & Sed & Awk', 'sed ''c\text''', 'Replace an entire line', 'sed ''/pattern/c\replaced line'' file.txt'),
('Grep & Sed & Awk', 'awk ''{print $1}''', 'Print the first column (field) of each line', 'awk ''{print $1}'' file.txt'),
('Grep & Sed & Awk', 'awk ''{print $0}''', 'Print the entire line', 'awk ''{print $0}'' file.txt'),
('Grep & Sed & Awk', 'awk ''{print $NF}''', 'Print the last column of each line', 'awk ''{print $NF}'' file.txt'),
('Grep & Sed & Awk', 'awk -F', 'Specify field separator (e.g., colon)', 'awk -F: ''{print $1}'' /etc/passwd'),
('Grep & Sed & Awk', 'awk ''/pattern/''', 'Print lines matching a pattern', 'awk ''/error/'' file.txt'),
('Grep & Sed & Awk', 'awk ''!/pattern/''', 'Print lines NOT matching a pattern', 'awk ''!/debug/'' file.txt'),
('Grep & Sed & Awk', 'awk ''$1 == "value"''', 'Print lines where the first column equals a value', 'awk ''$1 == "root"'' /etc/passwd'),
('Grep & Sed & Awk', 'awk ''$2 > 100''', 'Print lines where the second column is greater than 100', 'awk ''$2 > 100'' data.txt'),
('Grep & Sed & Awk', 'awk ''{sum += $1} END {print sum}''', 'Sum the values in the first column', 'awk ''{sum += $1} END {print sum}'' numbers.txt'),
('Grep & Sed & Awk', 'awk ''NR==5''', 'Print only the 5th line', 'awk ''NR==5'' file.txt'),
('Grep & Sed & Awk', 'awk ''NR>=2 && NR<=5''', 'Print lines 2 through 5', 'awk ''NR>=2 && NR<=5'' file.txt'),
('Grep & Sed & Awk', 'awk ''length($0) > 80''', 'Print lines longer than 80 characters', 'awk ''length($0) > 80'' file.txt'),
('Grep & Sed & Awk', 'awk ''{print NR, $0}''', 'Add line numbers to output', 'awk ''{print NR, $0}'' file.txt'),
('Grep & Sed & Awk', 'awk ''BEGIN { FS=":"; OFS="-" } {print $1,$2}''', 'Change output field separator', 'awk ''BEGIN { FS=":"; OFS="-" } {print $1,$2}'' /etc/passwd'),
('Grep & Sed & Awk', 'awk ''{ $1=""; print $0 }''', 'Remove the first column', 'awk ''{ $1=""; print $0 }'' file.txt'),
('Grep & Sed & Awk', 'awk ''!seen[$0]++''', 'Remove duplicate lines without sorting', 'awk ''!seen[$0]++'' file.txt'),
('Grep & Sed & Awk', 'awk ''{ gsub(/old/, "new"); print }''', 'Global substitution in awk', 'awk ''{ gsub(/foo/, "bar"); print }'' file.txt'),
('Grep & Sed & Awk', 'ps aux | grep | awk', 'Common pipeline to find a process ID', 'ps aux | grep nginx | awk ''{print $2}'''),
('Grep & Sed & Awk', 'grep -oP', 'Use Perl-compatible regular expressions (PCRE)', 'grep -oP "(?<=id=)[0-9]+" file.txt'),

-- === 10. CRON JOBS (50 Commands) ===
('Cron Jobs', 'crontab -e', 'Edit the crontab for the current user', 'crontab -e'),
('Cron Jobs', 'crontab -l', 'List the crontab for the current user', 'crontab -l'),
('Cron Jobs', 'crontab -r', 'Remove the crontab for the current user', 'crontab -r'),
('Cron Jobs', 'crontab -u user -e', 'Edit the crontab for a specific user (requires root)', 'sudo crontab -u www-data -e'),
('Cron Jobs', 'crontab -u user -l', 'List the crontab for a specific user', 'sudo crontab -u www-data -l'),
('Cron Jobs', '* * * * *', 'Run every minute', '* * * * * /path/to/script.sh'),
('Cron Jobs', '*/5 * * * *', 'Run every 5 minutes', '*/5 * * * * /path/to/script.sh'),
('Cron Jobs', '*/10 * * * *', 'Run every 10 minutes', '*/10 * * * * /path/to/script.sh'),
('Cron Jobs', '*/15 * * * *', 'Run every 15 minutes', '*/15 * * * * /path/to/script.sh'),
('Cron Jobs', '*/30 * * * *', 'Run every 30 minutes', '*/30 * * * * /path/to/script.sh'),
('Cron Jobs', '0 * * * *', 'Run at minute 0 (top of the hour) every hour', '0 * * * * /path/to/script.sh'),
('Cron Jobs', '30 * * * *', 'Run at minute 30 (bottom of the hour) every hour', '30 * * * * /path/to/script.sh'),
('Cron Jobs', '0 */2 * * *', 'Run every 2 hours at minute 0', '0 */2 * * * /path/to/script.sh'),
('Cron Jobs', '0 0 * * *', 'Run every day at midnight (00:00)', '0 0 * * * /path/to/script.sh'),
('Cron Jobs', '30 2 * * *', 'Run every day at 2:30 AM', '30 2 * * * /path/to/script.sh'),
('Cron Jobs', '0 12 * * *', 'Run every day at noon (12:00)', '0 12 * * * /path/to/script.sh'),
('Cron Jobs', '0 0 * * 0', 'Run every Sunday at midnight', '0 0 * * 0 /path/to/script.sh'),
('Cron Jobs', '0 0 * * 1', 'Run every Monday at midnight', '0 0 * * 1 /path/to/script.sh'),
('Cron Jobs', '0 0 * * 5', 'Run every Friday at midnight', '0 0 * * 5 /path/to/script.sh'),
('Cron Jobs', '0 0 * * 1-5', 'Run every weekday (Monday through Friday) at midnight', '0 0 * * 1-5 /path/to/script.sh'),
('Cron Jobs', '0 0 * * 0,6', 'Run every weekend (Saturday and Sunday) at midnight', '0 0 * * 0,6 /path/to/script.sh'),
('Cron Jobs', '0 0 1 * *', 'Run on the first day of every month at midnight', '0 0 1 * * /path/to/script.sh'),
('Cron Jobs', '0 0 15 * *', 'Run on the 15th of every month at midnight', '0 0 15 * * /path/to/script.sh'),
('Cron Jobs', '0 0 1 1 *', 'Run on January 1st every year at midnight', '0 0 1 1 * /path/to/script.sh'),
('Cron Jobs', '@reboot', 'Run a command once at startup', '@reboot /path/to/startup.sh'),
('Cron Jobs', '@yearly', 'Run once a year (same as "0 0 1 1 *")', '@yearly /path/to/script.sh'),
('Cron Jobs', '@annually', 'Run once a year (same as @yearly)', '@annually /path/to/script.sh'),
('Cron Jobs', '@monthly', 'Run once a month (same as "0 0 1 * *")', '@monthly /path/to/script.sh'),
('Cron Jobs', '@weekly', 'Run once a week (same as "0 0 * * 0")', '@weekly /path/to/script.sh'),
('Cron Jobs', '@daily', 'Run once a day (same as "0 0 * * *")', '@daily /path/to/script.sh'),
('Cron Jobs', '@midnight', 'Run once a day at midnight (same as @daily)', '@midnight /path/to/script.sh'),
('Cron Jobs', '@hourly', 'Run once an hour (same as "0 * * * *")', '@hourly /path/to/script.sh'),
('Cron Jobs', '> /dev/null 2>&1', 'Discard all output (stdout and stderr)', '* * * * * /path/to/script.sh > /dev/null 2>&1'),
('Cron Jobs', '>> /var/log/cron.log 2>&1', 'Append all output to a log file', '* * * * * /path/to/script.sh >> /var/log/cron.log 2>&1'),
('Cron Jobs', 'MAILTO=', 'Set email address for cron job output', 'MAILTO="admin@example.com"'),
('Cron Jobs', 'MAILTO=""', 'Disable sending email for cron job output', 'MAILTO=""'),
('Cron Jobs', 'PATH=', 'Set the PATH environment variable for cron jobs', 'PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin'),
('Cron Jobs', 'SHELL=', 'Set the shell to use for executing cron jobs', 'SHELL=/bin/bash'),
('Cron Jobs', 'HOME=', 'Set the home directory for cron jobs', 'HOME=/home/user'),
('Cron Jobs', '0-59/10 * * * *', 'Run at specific minute increments (0,10,20,30,40,50)', '0-59/10 * * * * /path/to/script.sh'),
('Cron Jobs', '15,45 * * * *', 'Run at minute 15 and 45 of every hour', '15,45 * * * * /path/to/script.sh'),
('Cron Jobs', '0 8-17 * * *', 'Run every hour during business hours (8 AM to 5 PM)', '0 8-17 * * * /path/to/script.sh'),
('Cron Jobs', '0 9,17 * * 1-5', 'Run at 9 AM and 5 PM on weekdays', '0 9,17 * * 1-5 /path/to/script.sh'),
('Cron Jobs', 'cat /etc/crontab', 'View the system-wide crontab file', 'cat /etc/crontab'),
('Cron Jobs', 'ls /etc/cron.*', 'List system cron directories (hourly, daily, weekly, monthly)', 'ls -la /etc/cron.daily'),
('Cron Jobs', '/etc/cron.allow', 'File to specify which users can use cron', 'cat /etc/cron.allow'),
('Cron Jobs', '/etc/cron.deny', 'File to specify which users are denied cron access', 'cat /etc/cron.deny'),
('Cron Jobs', 'systemctl status cron', 'Check the status of the cron service (Debian/Ubuntu)', 'systemctl status cron'),
('Cron Jobs', 'systemctl status crond', 'Check the status of the cron service (RHEL/CentOS)', 'systemctl status crond'),
('Cron Jobs', 'tail -f /var/log/cron', 'Monitor cron logs (RHEL/CentOS)', 'tail -f /var/log/cron'),
('Cron Jobs', 'grep CRON /var/log/syslog', 'View cron logs (Debian/Ubuntu)', 'grep CRON /var/log/syslog')
ON CONFLICT (command_name) DO UPDATE SET 
    description = EXCLUDED.description,
    example_usage = EXCLUDED.example_usage,
    category = EXCLUDED.category;
